"Component: Core Schema":
- source/modules/**/*

"Component: Workflows":
- .github/workflows/**/*

"Component: Guidelines & Documentation":
- source/docs/**/*

"Component: Utils":
- utils/**/*

"Component: Build":
- build.xml

