"Component: Build":
- build.xml

"Component: Core Schema":
- source/modules/**/*
- source/mei-source.xml

"Component: Customizations":
- customizations/**/*

"Component: Guidelines & Documentation":
- source/docs/**/*
- source/examples/**/*
- source/web/**/*

"Component: Images":
- source/images/**/*

"Component: Utils":
- utils/**/*

"Component: Workflows":
- .github/workflows/**/*