language: java
sudo: false
addons:
    apt:
        packages:
            - ant
            - jing

env:
 - PATH_TO_SAXON_JAR=Saxon-HE-9.6.0-7.jar PATH_TO_JING=/usr/bin/jing PATH_TO_TEI_STYLESHEETS=$TRAVIS_BUILD_DIR/Stylesheets
  global:
  - ENCRYPTION_LABEL: "73e61484bb4d"
  - COMMIT_AUTHOR_EMAIL: "andrew.hankinson@gmail.com"
# Pin the stylesheets to v7.41.0 (commit c3e4...)
before_install:
    - git clone https://github.com/TEIC/Stylesheets.git
    - cd Stylesheets && git checkout c3e4130ccb4f93700fda004c8e7fb037379ba268 && git reset --hard
    - cd ../
    - curl -O http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/9.6.0-7/Saxon-HE-9.6.0-7.jar

before_script:
    - ./build.sh build

script:
    - ./build.sh test
    - ./deploy-docs.sh