language: java
sudo: false
addons:
    apt:
        packages:
            - ant
            - jing

env:
 - PATH_TO_SAXON_JAR=$TRAVIS_BUILD_DIR/Saxon-HE-9.6.0-7.jar PATH_TO_JING=/usr/bin/jing PATH_TO_TEI_STYLESHEETS=$TRAVIS_BUILD_DIR/Stylesheets

before_install:
    - env
    - git clone --depth=1 https://github.com/TEIC/Stylesheets.git
    - curl -O http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/9.6.0-7/Saxon-HE-9.6.0-7.jar

before_script:
    - ./build.sh build

script:
    - ./build.sh test