language: java
sudo: required
before_install:
    - sudo apt-get install ant
    - sudo apt-get install jing
    - git clone --depth=1 https://github.com/TEIC/Stylesheets.git

before_script:
    - ./build.sh -t $TRAVIS_BUILD_DIR/Stylesheets/ all

script:
    - ./build.sh -t $TRAVIS_BUILD_DIR/Stylesheets/ test